# Generated by Django 4.0.4 on 2022-08-29 16:06

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=False, upload_to=store.models.product_image_location),
            preserve_default=False,
        ),
    ]
