# Generated by Django 4.0.4 on 2022-09-06 14:41

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_porduct', models.ImageField(blank=True, null=True, upload_to=store.models.more_img_product)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('product_attr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
